apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mall-web
  name: mall-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-web
  template:
    metadata:
      labels:
        app: mall-web    
    spec:
      containers:
      - image: pimdarpacr.azurecr.io/mall-web
        name: mall-web
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mall-web
  name: mall-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mall-web
  type: LoadBalancer
        
